// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppMyTienda;

namespace WebAppMyTienda.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200926025541_Ligas-tabla_01")]
    partial class Ligastabla_01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAppMyTienda.Models.Class.tbl_Ligas", b =>
                {
                    b.Property<int>("idliga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NombreLigas")
                        .HasColumnType("int");

                    b.HasKey("idliga");

                    b.ToTable("Tbl_Ligas");
                });
#pragma warning restore 612, 618
        }
    }
}
